import type { Metadata } from "next";
import { PT_Serif } from "next/font/google";
import "./globals.css";
import FullTemplate from "./_components/Template/FullTemplate";
import HalfTemplate from "./_components/Template/HalfTemplate";
import Footer from "./_components/common/Footer";
import Navbar from "./_components/common/Navbar";

// Load PT Serif font
const ptSerif = PT_Serif({
  variable: "--font-pt-serif",
  weight: ["400", "700"], // Adjust as needed
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Four Season Enterprices",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${ptSerif.variable} antialiased relative`}>
        <div>{children}</div>
        <div className="bg-[#F8FAFC]">
          <HalfTemplate>
            <Footer />
          </HalfTemplate>
        </div>
      </body>
    </html>
  );
}
